language: node_js
sudo: required
os:
  - linux
node_js:
  - "7"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
jobs:
  include:
    - stage: install
      script: npm install
    - stage: test:node
      script: npm run test:node
    - stage: test:browser
      script: npm run test:browser
    - stage: build
      script: npm run build
    - stage: lint
      script: npm run lint
    - stage: angular2
      script: (cd ./examples/angular2 && npm install && npm run build)
