language:        node_js
sudo:            required
os:
  - linux
node_js:
  - "10.6.0"
services:
  - docker

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - docker run -d -p 5984:5984 --rm --name rxdb-couchdb couchdb:2.1.1
script:
- travis_retry npm install --depth 0 --silent
- npm run build
- travis_retry npm run test:node
- travis_retry npm run test:fast
- travis_retry npm run test:browser
- travis_retry npm run test:performance
- travis_retry npm run test:typings
- travis_retry npm run test:couchdb
- npm run test:deps
- npm run lint

## examples
- (cd ./examples/angular2 && npm install > "/dev/null" 2>&1 && npm run build && travis_retry npm run test:build)
- (cd ./examples/vue && npm install > "/dev/null" 2>&1 && npm run lint && npm run build && travis_retry npm run test)
- (cd ./examples/react-native && npm install > "/dev/null" 2>&1 && travis_retry npm run test)
#no working on travis because of different chromium-version since  8.9.2018  - (cd ./examples/electron && npm install --depth 0 --silent && travis_retry npm run test)

## tutorials
- (cd ./test/tutorials/ && npm install --depth 0 --silent && travis_retry npm test)

- npm run build:size
