language:        node_js
sudo:            required
os:
  - linux
node_js:
  - "9.2.1"
services:
  - docker

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - docker run -d -p 5984:5984 --rm --name rxdb-couchdb couchdb:2.1.1
script:
- npm install --depth 0 --silent
- travis_retry npm run test:node
- travis_retry npm run test:fast
- travis_retry npm run test:browser
- travis_retry npm run test:performance
- travis_retry npm run test:typings
- travis_retry npm run test:couchdb
- npm run test:deps
- npm run build
- npm run lint
- (cd ./examples/angular2 && npm install --depth 0 --silent && npm run build && npm run test:build)
- (cd ./examples/vue && npm install --depth 0 --silent && npm run lint && npm run build && npm run test)
- (cd ./examples/react-native && npm install --depth 0 --silent && npm run test)
- (cd ./examples/electron && npm install --depth 0 --silent && travis_retry npm run test)
- npm run build:size
