language: node_js
node_js:
  - "7"
addons:
  firefox: latest
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "export CHROME_BIN=chromium-browser"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - sleep 3
