# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: start couchdb container
        run: docker run -d -p 5984:5984 --rm --name rxdb-couchdb couchdb:2.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 13.8.0

      # https://github.com/juliangruber/browser-run/issues/147
      - name: Setup X server install
        run: |
          sudo apt-get install xvfb
          export DISPLAY=:99.0
          Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &


      - name: install npm dependencies
        run: npm install --depth 0 --silent
      
#      - name: build
#        run: npm run build
      
#      - name: test:typings
#        run: npm run test:typings

#      - name: check types
#        run: npm run check-types

#      - name: test:deps
#        run: npm run test:deps

#      - name: test:circular
#        run: npm run test:circular

#      - name: lint
#        run: npm run lint
        
#      - name: npm run test:node
#        run: npm run test:node
  
#      - name: npm run test:fast
#        run: npm run test:fast

      # in the past we had tests that failed randomly
      # to prevent this we run the tests in fast-mode 10 times
#      - name: unit tests 10 times
#        run: for i in `seq 10`; do npm run test:fast; done

#      - name: npm run test:browser
#        uses: GabrielBB/xvfb-action@v1
#        with:
#          working-directory: ./ #optional
#          run: npm run test:browser
        
#      - name: npm run test:couchdb
#        run: npm run test:couchdb
        
#      - name: npm run test:performance
#        run: npm run test:performance

      - name: measure build size
        run: npm run build:size
        
      - name: test rollup build
        run: npm run build:rollup

      - name: test tutorials
        run: npm run build && (cd ./test/tutorials/ && npm install && npm test)
      
      - name: angular example
        run: npm run build && (cd ./examples/angular && npm install > "/dev/null" 2>&1 && npm run lint && npm run build && npm run test:build)

      - name: vue example
        run: npm run build && (cd ./examples/vue && npm install > "/dev/null" 2>&1 && npm run lint && npm run build && npm run test)

      - name: electron example
        run: npm run build && (cd ./examples/electron && npm install > "/dev/null" 2>&1 && npm run test)

      - name: electron-remote example
        run: npm run build && (cd ./examples/electron-remote && npm install > "/dev/null" 2>&1 && npm run test)

      - name: react example
        run: npm run build && (cd ./examples/react && npm install > "/dev/null" 2>&1 && npm run build && npm run test:build)

      - name: react-native example
        run: npm run build && (cd ./examples/react-native && npx yarn@1.13.0 install > "/dev/null" 2>&1 && npm run test && echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p && npm run test:bundle)

      - name: node example
        run: npm run build && (cd ./examples/node && npm install > "/dev/null" 2>&1 && npm run test)

      - name: graphql example
        run: npm run build && (cd ./examples/graphql && npm install > "/dev/null" 2>&1 && npm run build && npm run test:ci)
